spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost/processos
    username: postgres
    password: admin
  data:
    mongodb:
      uri: ${MONGO_TEST_URI:mongodb://localhost:27017}
      #database: ${MONGO_DB:prolink}
      #username: ${MONGO_USER:prolink}
      #password: ${MONGO_PASSWORD:prolink}
      #host: ${MONGO_HOST:127.0.0.1}
      #port: 27017
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
hibernate:
  hbm2ddl:
    auto: update
logging:
  config: classpath:logback-dev.xml
planilha:
  origem: Cadastro.xlsx
  destino: C:/TMP/LOGS
  senha: 1234
  agendamento: 0 0 0,13,18 ? * MON-FRI
cliente:
  agendamento: 0 0 0 ? * SUN